name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.13
          - 1.14
    name: Go ${{ matrix.go }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Install golint
        run: go install golang.org/x/lint/golint

      - name: Lint
        run: golint -set_exit_status ./...

      - name: Get dependencies
        run: go get -t -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -count=100 -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Ensure formatting
        run: |
          if [[ $(git ls-tree -r HEAD^{tree} . --full-name --name-only | \
                  grep '\.go$' | \
                  xargs -n 1 gofmt -d | \
                  wc -c) -ne 0 \
          ]]; then
            echo "please run gofmt on all the files"
            exit 1
          fi

      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash)
