name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Get dependencies
        run: go get -t -v ./...

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@c170e78287f338a4af0dc49e033e50e5a072d82b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Build
        run: |
          mkdir -p artifacts/usr/bin/
          go build -o artifacts/usr/bin/omegaup-logslurp \
            -ldflags "-X main.ProgramVersion=${{ steps.bump-version.outputs.tag }}" \
            github.com/omegaup/logslurp/cmd/omegaup-logslurp

      - name: Package
        run: |
          tar -cJf omegaup-logslurp.tar.xz --owner=root:0 --group=root:0 -C artifacts/ .

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.tag }}
          release_name: ${{ steps.bump-version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload omegaup-logslurp.tar.xz Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./omegaup-logslurp.tar.xz
          asset_name: omegaup-logslurp.tar.xz
          asset_content_type: application/octet-stream
